version: '2.0'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db:"${DB_PORT}"
      WORDPRESS_DB_PASSWORD: "${PASSWORD}"
    ports:
      - 80:80 # Expose http and https
      - 443:443
    networks:
      - back 
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    networks:
       - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${PASSWORD}"
    networks:
      - back
networks:
  back:
volumes:
  db_data:
  